#include "config.h"
#include <assert.h>
#include <bitcoin/chainparams.h>
#include <ccan/array_size/array_size.h>
#include <common/setup.h>
#include <stdio.h>
#include <common/utils.h>
#include <string.h>

/* AUTOGENERATED MOCKS START */
/* AUTOGENERATED MOCKS END */

/* The constants which say whether a node has upgraded.
 *
 * Two things are deliberately absent here, and their absence is the point.
 *
 * chain_hash is Bitcoin's genesis hash, unchanged, because a change of proof
 * of work is not a change of chain and there is nothing to pin.
 *
 * The BOLT 11 prefix is unchanged too: an invoice carries the same prefix it
 * always did. What separates it from one minted by a node which has not
 * upgraded is option_blake2b as an even bit in the `9` field. The prefixes
 * below are asserted to be exactly what upstream gives them, so that a future
 * change has to be deliberate rather than incidental.
 */
static const struct {
	const char *network;
	const char *lightning_hrp;
	u32 activation_height;
} expected[] = {
	{"bitcoin", "bc", 961640},
	{"regtest", "bcrt", 0},
	{"signet", "tbs", 0},
	{"testnet4", "tb", 150308},
	{"testnet", "tb", 0},
	{"liquid-regtest", "ert", 0},
	{"liquid", "ex", 0},
};

int main(int argc, char *argv[])
{
	common_setup(argv[0]);

	for (size_t i = 0; i < ARRAY_SIZE(expected); i++) {
		const struct chainparams *p
			= chainparams_for_network(expected[i].network);
		assert(p);

		/* Unchanged from upstream: the separation in BOLT 11 is the
		 * feature bit, not the prefix. */
		assert(streq(p->lightning_hrp, expected[i].lightning_hrp));

		assert(p->blake2b_activation_height
		       == expected[i].activation_height);
	}

	/* The activation height is what the gossip rule compares against, so
	 * it must be set on the chains that changed their proof of work and
	 * left alone everywhere else. Zero is what turns the rule off, and a stray
	 * non-zero value on a chain that never moved would refuse every
	 * channel announcement it ever saw. */
	assert(chainparams_for_network("bitcoin")->blake2b_activation_height
	       == 961640);
	assert(chainparams_for_network("testnet4")->blake2b_activation_height
	       == 150308);
	assert(chainparams_for_network("regtest")->blake2b_activation_height
	       == 0);

	/* chain_hash stays Bitcoin's genesis. This is Bitcoin; only the proof
	 * of work changed, so the network is not given an identity of its
	 * own. */
	{
		struct bitcoin_blkid genesis;

		assert(bitcoin_blkid_from_hex("000000000019d6689c085ae165831e93"
					      "4ff763ae46a2a6c172b3f1b60a8ce26f",
					      64, &genesis));
		assert(bitcoin_blkid_eq(
			&chainparams_for_network("bitcoin")->genesis_blockhash,
			&genesis));
	}

	/* The table above must cover every network this build defines, so that
	 * one added later cannot quietly default to a height nobody checked.
	 * Counting the separators avoids needing a mutable copy: these test
	 * binaries link against chainparams.o and libcommon.a only. */
	{
		const char *all = chainparams_get_network_names(tmpctx);
		size_t count = 1;

		assert(all && *all);

		for (const char *p = all; *p; p++) {
			if (*p == ',')
				count++;
		}

		/* If this fires, a network was added: put it in the table
		 * above with the height it should carry, which is zero unless
		 * it is a chain that changed its proof of work. */
		assert(count == ARRAY_SIZE(expected));
	}

	common_shutdown();

	return 0;
}
